/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandIdentityRouteImport } from './routes/brand-identity'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PackagingDesignsRouteImport } from './routes/packaging-designs'
import { Route as PerformanceMarketingRouteImport } from './routes/performance-marketing'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WebsiteBuildingRouteImport } from './routes/website-building'
import { Route as WorkRouteImport } from './routes/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIdentityRoute = BrandIdentityRouteImport.update({
  id: '/brand-identity',
  path: '/brand-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingDesignsRoute = PackagingDesignsRouteImport.update({
  id: '/packaging-designs',
  path: '/packaging-designs',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceMarketingRoute = PerformanceMarketingRouteImport.update({
  id: '/performance-marketing',
  path: '/performance-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteBuildingRoute = WebsiteBuildingRouteImport.update({
  id: '/website-building',
  path: '/website-building',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/contact': typeof ContactRoute
  '/packaging-designs': typeof PackagingDesignsRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/social-media': typeof SocialMediaRoute
  '/studio': typeof StudioRoute
  '/website-building': typeof WebsiteBuildingRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/contact': typeof ContactRoute
  '/packaging-designs': typeof PackagingDesignsRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/social-media': typeof SocialMediaRoute
  '/studio': typeof StudioRoute
  '/website-building': typeof WebsiteBuildingRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/contact': typeof ContactRoute
  '/packaging-designs': typeof PackagingDesignsRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/social-media': typeof SocialMediaRoute
  '/studio': typeof StudioRoute
  '/website-building': typeof WebsiteBuildingRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-identity'
    | '/contact'
    | '/packaging-designs'
    | '/performance-marketing'
    | '/social-media'
    | '/studio'
    | '/website-building'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-identity'
    | '/contact'
    | '/packaging-designs'
    | '/performance-marketing'
    | '/social-media'
    | '/studio'
    | '/website-building'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/brand-identity'
    | '/contact'
    | '/packaging-designs'
    | '/performance-marketing'
    | '/social-media'
    | '/studio'
    | '/website-building'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandIdentityRoute: typeof BrandIdentityRoute
  ContactRoute: typeof ContactRoute
  PackagingDesignsRoute: typeof PackagingDesignsRoute
  PerformanceMarketingRoute: typeof PerformanceMarketingRoute
  SocialMediaRoute: typeof SocialMediaRoute
  StudioRoute: typeof StudioRoute
  WebsiteBuildingRoute: typeof WebsiteBuildingRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-identity': {
      id: '/brand-identity'
      path: '/brand-identity'
      fullPath: '/brand-identity'
      preLoaderRoute: typeof BrandIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging-designs': {
      id: '/packaging-designs'
      path: '/packaging-designs'
      fullPath: '/packaging-designs'
      preLoaderRoute: typeof PackagingDesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-marketing': {
      id: '/performance-marketing'
      path: '/performance-marketing'
      fullPath: '/performance-marketing'
      preLoaderRoute: typeof PerformanceMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-building': {
      id: '/website-building'
      path: '/website-building'
      fullPath: '/website-building'
      preLoaderRoute: typeof WebsiteBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandIdentityRoute: BrandIdentityRoute,
  ContactRoute: ContactRoute,
  PackagingDesignsRoute: PackagingDesignsRoute,
  PerformanceMarketingRoute: PerformanceMarketingRoute,
  SocialMediaRoute: SocialMediaRoute,
  StudioRoute: StudioRoute,
  WebsiteBuildingRoute: WebsiteBuildingRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
